[package]
name = "broot"
version = "0.12.2"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
documentation = "https://dystroy.org/broot"
description = "Fuzzy Search + tree + cd"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"
build = "build.rs"

[dependencies]
chrono = "0.4"
regex = "1.3"
lazy_static = "1.4"
directories = "2.0"
toml = "0.5"
custom_error = "1.6"
log = "0.4"
simplelog = "0.7"
clap = "2.33"
glob = "0.3"
crossbeam = "0.7"
open = "1.3.2"
crossterm = "0.15.0"
umask = "0.1.7"
minimad = "0.6.3"
termimad = "0.8.12"
id-arena = "2.2.1"
lazy-regex = "0.1"
pathdiff = "0.1.0"

[dependencies.git2]
version = "0.11"
default-features = false

[dev-dependencies]
criterion = "0.3"

[target.'cfg(unix)'.dependencies]
users = "0.9"

[target.'cfg(windows)'.dependencies]
is_executable = "0.1"

[build-dependencies]
clap = "2.33"

[profile.release]
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size

[[bench]]
name = "fuzzy"
harness = false

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
# opener = { path = "../opener/opener" }
# umask = { path = "../umask" }

