[package]
name = "broot"
version = "0.20.3"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
documentation = "https://dystroy.org/broot"
description = "A new file manager"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"
build = "build.rs"
exclude = ["website", "broot*.zip"]

[features]
default = []
client-server = []

[dependencies]
ansi_colours = "1.0"
bet = "0.3.4"
clap = { version="2.33", default-features=false, features=["suggestions"] }
cli-clipboard = {path="/home/zx/workspace/git/cli-clipboard"}
chrono = "0.4"
crossbeam = "0.7"
crossterm = "0.17.7"
custom_error = "1.6"
directories = "2.0"
file-size = "1.0.2"
git2 = { version="0.11", default-features=false }
glob = "0.3"
id-arena = "2.2.1"
image = "0.23"
lazy-regex = "0.1.3"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
minimad = "=0.6.5"
open = "1.4"
memmap = "0.7"
pathdiff = "0.1.0"
phf = { version = "0.8", features = ["macros"] }
rayon = "1.3"
regex = "1.3"
secular = "0.2"
simplelog = "0.7"
strict = "0.1.4"
syntect = "4.2"
termimad = "0.8.26"
toml = "0.5"
umask = "1.0"
unicode-width = "0.1.8"


[dev-dependencies]
criterion = "0.3.1"

[target.'cfg(unix)'.dependencies]
users = "0.9"

[target.'cfg(windows)'.dependencies]
is_executable = "0.1"

[build-dependencies]
clap = "2.33"

[profile.release]
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size

[[bench]]
name = "fuzzy"
harness = false

[[bench]]
name = "path_normalization"
harness = false

[patch.crates-io]
# bet = { path = "../bet" }
# lazy-regex = { path = "../lazy-regex" }
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
# opener = { path = "../opener/opener" }
# umask = { path = "../umask" }
# secular = { path = "../secular" }
#Â strict = { path = "../strict" }
