[package]
name = "broot"
version = "1.7.6-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
documentation = "https://dystroy.org/broot"
description = "A new file manager"
edition = "2021"
keywords = ["cli", "fuzzy", "tree", "search", "file"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"
build = "build.rs"
rust-version = "1.56"
exclude = ["website", "broot*.zip"]

[features]
default = []
clipboard = ["terminal-clipboard"]

[dependencies]
ahash = { version = "0.7", features = ["serde"] }
ansi_colours = "1.0"
base64 = "0.13"
bet = "1.0"
char_reader = "0.1"
clap = { version="2.33", default-features=false, features=["suggestions", "color"] }
cli-log = "2.0"
chrono = "0.4"
crossbeam = "0.8"
crossterm = "0.22.1"
custom_error = "1.6"
deser-hjson = "1.0.2"
directories = "3.0"
file-size = "1.0.3"
fnv = "1.0.7"
git2 = { version="0.13", default-features=false }
glob = "0.3"
id-arena = "2.2.1"
image = "0.23.14"
lazy-regex = "2.2.2"
libc = "0.2"
once_cell = "1.7"
open = "2.0"
memmap = "0.7"
pathdiff = "0.2"
phf = { version = "0.9", features = ["macros"] }
rayon = "1.5"
regex = "1.5"
secular = { version = "1.0", features = ["normalization"] }
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.6"
splitty = "0.1"
strict = "0.1.4"
syntect = "4.6"
tempfile = "3.2"
termimad = "0.20.0"
terminal-clipboard = { version = "0.3.1", optional = true }
toml = "0.5"
umask = "1.0"
unicode-width = "0.1.8"

[dev-dependencies]
glassbench = "0.3.0"

[target.'cfg(unix)'.dependencies]
lfs-core = "0.4.2"
users = "0.11"

[target.'cfg(windows)'.dependencies]
is_executable = "1.0.1"

[build-dependencies]
clap = "2.33"

[profile.dev]
debug = false

[profile.release]
debug = false
lto = true
codegen-units = 1 # this removes a few hundred bytes from the final exec size

[[bench]]
name = "fuzzy"
harness = false
[[bench]]
name = "toks"
harness = false
[[bench]]
name = "composite"
harness = false
[[bench]]
name = "path_normalization"
harness = false

[patch.crates-io]
# bet = { path = "../bet" }
# cli-log = { path = "../cli-log" }
# crossterm = { path = "../crossterm-rs/crossterm" }
# deser-hjson = { path = "../deser-hjson" }
# glassbench = { path = "../glassbench" }
# lazy-regex = { path = "../lazy-regex" }
# lfs-core = { path = "../lfs-core" }
# minimad = { path = "../minimad" }
# secular = { path = "../secular", features=["normalization"] }
#Â strict = { path = "../strict" }
# termimad = { path = "../termimad" }
# terminal-clipboard = { path = "../terminal-clipboard" }
# umask = { path = "../umask" }
