[package]
name = "broot"
version = "0.4.6"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
description = "Fuzzy Search + tree + cd"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "linux"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
termion = "1.5.1"
regex = "1"
lazy_static = "1.2"
directories = "1.0"
toml = "0.4.9"
custom_error = "1.3.0"
log = "0.4"
simplelog = "0.5"
clap = "2.32"
glob = "0.2"
users = "0.8"

