site_name: Broot
site_description: 'Broot, a tree oriented file manager'
site_url: https://dystroy.org/broot
repo_url: https://github.com/Canop/broot
edit_uri: ''

nav:
        - Why: index.md
        - Install:
                - Install broot: install.md
                - Install br: install-br.md
                - Common Problems: common-problems.md
        - Usage:
                - Launch: launch.md
                - Search and Navigate: navigation.md
                - Tree View: tree_view.md
                - Help screen: help.md
                - Verbs & Commands: verbs.md
                - Panels: panels.md
                - Staging Area: staging-area.md
                - Tree export: export.md
                - Tips & tricks: tricks.md
                - Common file operations: file-operations.md
                - Client - Server: remote.md
                - Reference - The input: input.md
        - Conf:
                - Config files: conf_file.md
                - Verbs and shortcuts: conf_verbs.md
                - Skins: skins.md
                - Icons: icons.md
                - Modal Mode: modal.md
        - Community: community.md

extra_css:
        - css/extra.css
        - css/tab-langs.css
        - css/link-to-dystroy.css

extra_javascript:
        - js/tab-langs.js
        - js/link-to-dystroy.js

theme:
        name: null
        custom_dir: broot_theme/
        highlightjs: true

markdown_extensions:
        - admonition
        - def_list
